# Etapa de construcción
FROM golang:1.22 AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o go-rest ./cmd/rest-api

# Etapa de ejecución
FROM alpine:latest
COPY --from=builder /app/go-rest /go-rest
EXPOSE 8080
CMD ["/go-rest"]