FROM golang:1.22 AS builder
WORKDIR /app
COPY . .
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -o grpc-server-rabbit ./cmd/grpc-server-rabbit

FROM alpine:latest
COPY --from=builder /app/grpc-server-rabbit /grpc-server-rabbit
CMD ["/grpc-server-rabbit"]