persistence:
  enabled: true
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  size: 1Gi
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Redis
      type: redis-datasource
      access: proxy
      url: redis-service.tweets-clima.svc.cluster.local:6379
      jsonData:
        password: password123
        version: 7
    - name: Valkey
      type: redis-datasource
      access: proxy
      url: valkey-service.tweets-clima.svc.cluster.local:6379
      jsonData:
        password: password123
        version: 7
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/default
dashboards:
  default:
    tweet-dashboard:
      gnetId: null
      revision: 1
      datasource: Redis