apiVersion: apps/v1
kind: Deployment
metadata:
  name: valkey
  namespace: tweets-clima
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - name: valkey
        image: valkey/valkey:latest
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: valkey-storage
          mountPath: /data
      volumes:
      - name: valkey-storage
        persistentVolumeClaim:
          claimName: valkey-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: tweets-clima
spec:
  selector:
    app: valkey
  ports:
  - port: 6379
    targetPort: 6379
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: valkey-pvc
  namespace: tweets-clima
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi