[package]
name = "rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }